### ISSUE TITLE
How to compile the ipc and manage server  !

### ISSUE THREAD

**Issue by oneway3124** [caiqiangaka/Brain#1]
How to compile the ipc and manage server  !

**Comment by caiqiangaka** [comment]
1 Download codes to your ubuntu system
2 cd xxxx/ipc
3 make
4 cd xxxx/manage_server
5 make

**Comment by caiqiangaka** [comment]
Compile zebra:
1 cd xxxx/zebra
2 ./configure  --disable-ipv6
3 make
4 sudo ./zebra/zebra -P 23
5 open a new terminal : telnet 127.0.0.1
